// Generated by CoffeeScript 1.7.1
(function() {
  if ((typeof exports !== "undefined" && exports !== null) && ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null)) {
    require("../mate").enableAllFeatures();
  } else {
    $mate.enableAllFeatures();
  }

  new Test("root").add(function() {
    return unit(' new Date("2014-02-03T18:19:25.987").equals(new Date("2014-02-03T18:19:25.987"))=true ');
  }).add(function() {
    var Obj, obj;
    Obj = (function() {
      function Obj() {
        this.onClick = eventField();
      }

      Obj.prototype.makeClick = function() {
        return this.onClick.fire();
      };

      return Obj;

    })();
    obj = new Obj();
    obj.onClick.bind(function() {
      return finish();
    });
    return obj.makeClick();
  }).add(function() {
    return console.logt(3);
  }).add("Object.is", function() {
    unit(' Object.is(5,5)=true ');
    unit(' Object.is(5,7)=false ');
    unit(' Object.is(0,-0)=false ');
    unit(' Object.is(0,0)=true ');
    unit(' Object.is(NaN,NaN)=true ');
    return unit(' Object.is({},{})=false ');
  }).run();

}).call(this);
