// Generated by CoffeeScript 1.7.1
(function() {
  if (typeof npmMate === "undefined" || npmMate === null) {
    require("../mate");
  }

  new Test("root").add(function(my, I) {
    return I.wish(' new Date("2014-02-03T18:19:25.987").equals(new Date("2014-02-03T18:19:25.987"))=true ');
  }).add(function(my, I) {
    var Obj, obj;
    Obj = (function() {
      function Obj() {
        this.onClick = eventField();
      }

      Obj.prototype.makeClick = function() {
        return this.onClick.fire();
      };

      return Obj;

    })();
    obj = new Obj();
    obj.onClick.bind(function() {
      return I.end();
    });
    return obj.makeClick();
  }).add(function() {
    return console.logt(3);
  }).add("Object.is", function(my, I) {
    I.wish(' Object.is(5,5)=true ');
    I.wish(' Object.is(5,7)=false ');
    I.wish(' Object.is(0,-0)=false ');
    I.wish(' Object.is(0,0)=true ');
    I.wish(' Object.is(NaN,NaN)=true ');
    return I.wish(' Object.is({},{})=false ');
  }).run();

}).call(this);
