// Generated by CoffeeScript 1.6.3
/*

This is to test the "test". The output should look something like that:

2014-05-02T09:32:42.933Z Success: 6, Failure: 3, Pending: 2
2014-05-02T09:32:43.931Z Success: 6, Failure: 4, Pending: 1
2014-05-02T09:32:44.933Z Success: 6, Failure: 4, Pending: 1
2014-05-02T09:32:45.934Z Success: 7, Failure: 4, Pending: 0

Failure "simple test 1":
function () {
      return 1 + 2 + 3 === 7;
    }

Failure "simple test 1":
function () {
      return assert(false);
    }
...

Failure "simple test 1":
function () {
      throw new Error();
    }
...

Failure "Test_0":
function () {
    return true === false;
  }

Completed. 4 failures.
*/

if ((typeof exports !== "undefined" && exports !== null) && ((typeof module !== "undefined" && module !== null ? module.exports : void 0) != null)) {
  require("../mate");
}

$mate.test.add("simple test 1", [
  function() {
    return 1 + 2 + 3 === 6;
  }, function() {
    return 1 + 2 + 3 === 7;
  }, function() {
    return "hello".substr(1, 1) === "e";
  }, function() {
    return assert(true);
  }, function() {
    return assert(false);
  }, function() {}, function() {
    return void 0;
  }, function() {
    return null;
  }, function() {
    throw new Error();
  }
]).add("simple test 2", function(state) {
  return setTimeout(function() {
    return state(true);
  }, 2500);
}).add(function() {
  return true === false;
}, 1000).run();
